### ISSUE TITLE
COS URL is producing error with a shortened URL when retrieving results

### ISSUE THREAD

**Issue by aa7955** [IBM-Cloud/sql-query-clients#11]
A user can enter a COS URL:

```
cos://s3.us-south.objectstorage.softlayer.net/my_bucket/
```

But when shortening it to:

```
cos://us-south/my_bucket/
```

It sends the query and processes it, but fails when retrieving the results with something like:

```
   print(sqlClient.get_result(traffic))
  File "/Users/ajalger/code/sql-query-clients/Python/ibmcloudsql/SQLQuery.py", line 152, in get_result
    validate_cert=False)
  File "/usr/local/lib/python3.6/site-packages/tornado/httpclient.py", line 102, in fetch
    self._async_client.fetch, request, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 289, in <lambda>
    future, lambda future: callback(future.result()))
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/tornado/tcpclient.py", line 177, in connect
    addrinfo = yield self.resolver.resolve(host, port, af)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 363, in submit
    future.set_result(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 391, in resolve
    addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
Exception ignored in: <bound method HTTPClient.__del__ of <tornado.httpclient.HTTPClient object at 0x10c129f60>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/httpclient.py", line 82, in __del__
  File "/usr/local/lib/python3.6/site-packages/tornado/httpclient.py", line 87, in close
  File "/usr/local/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 118, in close
  File "/usr/local/lib/python3.6/site-packages/tornado/httpclient.py", line 203, in close
RuntimeError: inconsistent AsyncHTTPClient cache
```
It works in the UI so I think it has something to do with parsing perhaps?

When trying to delete objects from a bucket, a better error is returned which probably means that it's not connecting properly:

```
ibm_botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://us-south/sql-e84e2979-43b2-4013-9002-15ec66b23daf?delete"
```

Perhaps because `https` is used instead of `cos`. That comes from the latest commit.

**Comment by torsstei** [comment]
@aa7955 Yes, that's an insufficiency. The alias mapping is done inside SQL Query service and that's why it only works for COS URLs used in the FROM clause but fails when using an alias in the target URL using the ibmcloudsql Python client because here the endpoint is also used to talk to the COS API directly in the get_result() method. I've fixed that now and included an explicit alias-2-endpoint mapping in the Python client. Published this also in v0.2.2.
