### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by shawnzhu** [IBM-Cloud/sql-query-clients#96]
**Describe the bug**
one required package is not installed when installing `ibmcloudsql`

**To Reproduce**
1. Create python 3.7 runtime by running `docker run -it --rm python:3.8-buster`
2. Run `pip install ibmcloudsql`
3. Run `python3`
4. Run python code `import ibmcloudsql`
5. See error:

```Python
Python 3.7.9 (default, Aug 18 2020, 03:27:13) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibmcloudsql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ibmcloudsql/__init__.py", line 19, in <module>
    from .SQLQuery import SQLQuery
  File "/usr/local/lib/python3.7/site-packages/ibmcloudsql/SQLQuery.py", line 33, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Expected behavior**
the module `ibmcloudsql` should be imported successfully.

**Additional context**
I saw this new package was introduced by #93

**Comment by shawnzhu** [comment]
I'm curious how it passes CI, and I guess it is the python virtualenv from Travis CI has `packaging` installed already.

**Comment by shawnzhu** [comment]
This problem has broken my production data pipeline since Aug 23rd, I will jump in to fix it
